# synthetic_diff_geo.tex: synthetic_diff_geo.md header.tex
# 	pandoc -H header.tex -f markdown+tex_math_single_backslash \
# 	  --number-sections \
# 	  --toc \
# 	  --top-level-division=chapter \
# 	  synthetic_diff_geo.md -o synthetic_diff_geo.tex

synthetic_diff_geo.pdf: synthetic_diff_geo.tex
	tectonic synthetic_diff_geo.tex
